name: e_commerce_flutter
description: E-Commerce App built in flutter using GetX

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animations: ^2.0.7
  bottom_navy_bar: ^6.0.0
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.14.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.1
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.0.4
  flutter_stripe: ^10.0.0
  http: ^1.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/bg_image.svg
    - assets/images/logo_icon.svg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/smartstockpro.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
 