name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install Flutter
      uses: subosito/flutter-action@v1

    - name: Get Flutter packages
      run: flutter pub get

    - name: Build APK
      run: flutter build apk

    - name: Build iOS
      run: |
        sudo xcode-select --switch /Applications/Xcode_12.4.app
        flutter build ios --release --no-codesign